language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO_VERSION=1.8.3
  - DJANGO_VERSION=1.7.9
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.4.21
install: pip install --use-mirrors -q Django==$DJANGO_VERSION
script: tests/test.sh
matrix:
  exclude:
    - python: "3.4"
      env: DJANGO_VERSION=1.4.21
